-- DROP TABLE  city CASCADE;
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (1, 'Киев', true, 09);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (2, 'Харьков', true, 19);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (3, 'Одесса', true, 14);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (4, 'Днепр', true, 03);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (5, 'Донецк', true, 04);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (6, 'Запорожье', true, 07);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (7, 'Львов', true, 12);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (8, 'Кривой Рог', true, 11);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (9, 'Николаев', true, 13);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (10, 'Мариуполь', true, 04);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (11, 'Луганск', true, 11);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (12, 'Винница', true, 01);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (13, 'Макеевка', true, 04);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (14, 'Севастополь', true, 10);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (15, 'Симферополь', true, 10);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (16, 'Херсон', true, 20);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (17, 'Горловка', true, 04);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (18, 'Кропивницкий', true, 25);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (19, 'Луцк', true, 02);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (20, 'Краматорск', true, 04);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (21, 'Мелитополь', true, 07);
INSERT INTO city (id_city, name_city, is_root, ref_id_region) VALUES (22, 'Ужгород', true, 06);