-- DROP  TABLE  region CASCADE;
INSERT INTO region(id_region, title_region) VALUES (01 ,'Винницкая');
INSERT INTO region(id_region, title_region) VALUES (02,'Волынская');
INSERT INTO region(id_region, title_region) VALUES (03,'Днепропетровская');
INSERT INTO region(id_region, title_region) VALUES (04,'Донецкая');
INSERT INTO region(id_region, title_region) VALUES (05,'Житомирская');
INSERT INTO region(id_region, title_region) VALUES (06,'Закарпатская');
INSERT INTO region(id_region, title_region) VALUES (07,'Запорожская');
INSERT INTO region(id_region, title_region) VALUES (08,'Ивано-Франковская');
INSERT INTO region(id_region, title_region) VALUES (09,'Киевская');
INSERT INTO region(id_region, title_region) VALUES (25,'Кировоградская');
INSERT INTO region(id_region, title_region) VALUES (10,'Крым');
INSERT INTO region(id_region, title_region) VALUES (11,'Луганская');
INSERT INTO region(id_region, title_region) VALUES (12,'Львовская');
INSERT INTO region(id_region, title_region) VALUES (13,'Николаевская');
INSERT INTO region(id_region, title_region) VALUES (14,'Одесская');
INSERT INTO region(id_region, title_region) VALUES (15,'Полтавская');
INSERT INTO region(id_region, title_region) VALUES (16,'Ровенская');
INSERT INTO region(id_region, title_region) VALUES (17,'Сумская');
INSERT INTO region(id_region, title_region) VALUES (18,'Тернопольская');
INSERT INTO region(id_region, title_region) VALUES (19,'Харьковская');
INSERT INTO region(id_region, title_region) VALUES (20,'Херсонская');
INSERT INTO region(id_region, title_region) VALUES (21,'Хмельницкая');
INSERT INTO region(id_region, title_region) VALUES (22,'Черкасская');
INSERT INTO region(id_region, title_region) VALUES (23,'Черниговская');
INSERT INTO region(id_region, title_region) VALUES (24,'Черновицкая');
